### ISSUE TITLE
代码高亮如何实现

### ISSUE THREAD

**Issue by itcats** [biezhi/terse#3]
大大。目前无法实现代码高亮，要怎么办，现在的情况是黑底白字。

**Comment by hellokaton** [comment]
代码高亮已经实现了啊，你看我的博客地址。当前版本的代码就有

**Comment by itcats** [comment]
所以我奇怪啊，我也没用什么插件，也就改个头像，怎么就不亮了呢。变黑白电视了。

**Comment by hellokaton** [comment]
你的站点是什么我看看

**Comment by itcats** [comment]
http://it.wenxixi.com

**Comment by hellokaton** [comment]
你的站点中没有代码高亮的片段，你可以直接更新最新代码或者手动添加。手动添加太麻烦，如果你有自定义配置，先保存一份。

**Comment by itcats** [comment]
好的，谢谢，晚上我去看看，在车上了。现在不太方便😜

**Comment by hellokaton** [comment]
好的，你好像用的是0.0.1版本的，更新了好多呢 :open_mouth:

**Comment by itcats** [comment]
纳尼，估计是因为不是github上下载的原因，我好像是一论坛上看到的，有zip就直接下了。回去我更新下。

**Comment by hellokaton** [comment]
好吧，应该是的。

**Comment by itcats** [comment]
ok，弄好了，：）

**Comment by houzi-** [comment]
我也出现该情况！http://www.router008.com 直接变成白纸黑字了
